export const SKILLS: { [key: string]: string[] } = {
  ncsoft: [
    'javascript',
    'typescript',
    'react',
    'nextjs',
    'svelte',
    'jquery',
    'pnpm',
    'yarn',
    'webpack',
    'rollup',
    'jest',
    'vitest',
    'playwright',
    'docker',
    'git',
  ],
  mbisolution: [
    'javascript',
    'typescript',
    'react',
    'nextjs',
    'd3',
    'jquery',
    'yarn',
    'webpack',
    'rollup',
    'storybook',
    'cypress',
    'aws',
    'docker',
    'jenkins',
    'bash',
    'xcode',
    'git',
  ],
  qualson: [
    'javascript',
    'typescript',
    'react',
    'redux',
    'webpack',
    'yarn',
    'git',
  ],
  mtechcrew: [
    'javascript',
    'jquery',
    'react',
    'redux',
    'npm',
    'gulp',
    'webpack',
    'git',
  ],
  nemusoft: ['javascript', 'jquery', 'grunt', 'npm', 'git'],
  helloworld: [
    'javascript',
    'nodejs',
    'angularjs',
    'bootstrap',
    'jquery',
    'npm',
    'objectivec',
    'xcode',
    'git',
  ],
};
