import {
  ColorSchemeScript,
  Container,
  MantineProvider,
  createTheme,
} from '@mantine/core';
import '@mantine/core/styles.css';
import { Header } from 'components/header';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: "Kobe's Blog",
  description: 'Generated by Jaesung Lee',
  icons: {
    icon: '/favicon.ico',
  },
};

const theme = createTheme({
  cursorType: 'pointer',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>
      <body>
        <MantineProvider theme={theme} defaultColorScheme="auto">
          <Header />
          <Container mt={100}>{children}</Container>
        </MantineProvider>
      </body>
    </html>
  );
}
